
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces
    command: sleep infinity

  db:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    volumes:
      - postgres-data-hn-metrics:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data-hn-metrics:

